[[language]]
name = "timesheet"
scope = "source.times"
injection-regex = ""
file-types = ["times"]
language-id = "timesheeet"
shebangs = []
roots = []

[[language]]
name = "haskell"
auto-format = true

[[language]]
name = "json"
auto-format = true

[[language]]
name = "toml"
auto-format = true

[language-server.rust-analyzer.config]
check.command = "clippy"

[language-server.rust-analyzer.config.cargo]
features = "all"
cfgs = ["debug_assertions", "miri", "kani", "kani-ra"]

[language-server.codebook]
command = "codebook-lsp"
args = ["serve"]

[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[language-server.harper-ls.config.harper-ls]
userDictPath = ""
fileDictPath = ""
diagnosticSeverity = "hint"
isolateEnglish = false
dialect = "American"
maxFileLength = 120000

[language-server.harper-ls.config.harper-ls.linters]
SpellCheck = true
SpelledNumbers = false
AnA = true
SentenceCapitalization = true
UnclosedQuotes = true
WrongQuotes = false
LongSentences = true
RepeatedWords = true
Spaces = true
Matcher = true
CorrectNumberSuffix = true

[language-server.harper-ls.config.harper-ls.codeActions]
ForceStable = false

[language-server.harper-ls.config.harper-ls.markdown]
IgnoreLinkTitle = false

[language-server.vale]
command = "vale-ls"

[[language]]
name = "markdown"
scope = "source.md"
injection-regex = "md|markdown"
file-types = [
  "md",
  "livemd",
  "markdown",
  "mdx",
  "mkd",
  "mkdn",
  "mdwn",
  "mdown",
  "markdn",
  "mdtxt",
  "mdtext",
  "workbook",
  { glob = "PULLREQ_EDITMSG" },
]
roots = [".marksman.toml"]
language-servers = [
  "marksman",
  "markdown-oxide",
  "codebook",
  "harper-ls",
  "vale",
]
indent = { tab-width = 2, unit = "  " }
block-comment-tokens = { start = "<!--", end = "-->" }
